/**
 * @wp/design-tokens - DTCG (Design Tokens Community Group) JSON token source
 * (`src/tokens/*.tokens.json`), generated by `pnpm tokens:build` (build.mjs,
 * Style Dictionary) into CSS custom properties (`css/tokens.css`) + a
 * Tailwind v4 CSS-first theme (`css/tailwind-theme.css`). This is the single
 * visual contract shared by @wp/ui and every UI (app/frontend, admin/frontend,
 * website). No runtime dependencies.
 */
export const packageName = '@wp/design-tokens' as const;

export { tokens, TOKEN_CSS_PATH, TAILWIND_THEME_CSS_PATH } from './tokens.generated.js';
