-- P24 (groups-messaging) Unit U1 - migration 0067. Extends the existing
-- `notification_kind` enum (migration 0048) with `group_forbidden` (a send
-- into a group came back forbidden - the group was left/removed/converted to
-- announce-only against our role, etc.) - see
-- `packages/domain/src/enums/index.ts`'s `NOTIFICATION_KINDS` (appended, same
-- order) and `packages/domain/src/notifications/kinds.ts`'s
-- `NOTIFICATION_KIND_REGISTRY` for the severity/channel/dedupe-scope entry
-- `db/tests/enum-parity.test.ts` requires to already agree.
--
-- Nothing but the one ADD VALUE statement - same reasoning as migration 0059:
-- `ALTER TYPE ... ADD VALUE` cannot be used in the same transaction as a
-- statement that reads the new value (PG12+), so this file stays minimal by
-- design (no companion CREATE/ALTER of any other object here).
ALTER TYPE notification_kind ADD VALUE 'group_forbidden';
