/**
 * enums-exports.ts (P20 Unit U2, step 3) - the enum re-export block split out
 * of `index.ts` (that barrel sat at 298/300 lines; adding the new
 * `contacts/index.ts` export block would have breached the `max-lines: 300`
 * cap in `core-invariants.md`). Sibling-module split, same idiom as
 * `session-worker-discovery-wiring.ts` - never trim a contract comment to
 * make room, split instead.
 */
export {
  PG_ENUMS,
  JOB_STATUSES,
  type PgJobStatus,
  JOB_PRIORITIES,
  type JobPriority,
  JOB_KINDS,
  type JobKind,
  ATTEMPT_STATES,
  type AttemptState,
  WA_HEALTHS,
  type WaHealth,
  WA_LINK_STATES,
  type WaLinkState,
  INSTANCE_DESIRED_STATES,
  type InstanceDesiredState,
  PAUSE_REASONS,
  type PauseReason,
  CLIENT_STATUSES,
  type ClientStatus,
  USER_STATUSES,
  type UserStatus,
  MEMBERSHIP_ROLES,
  type MembershipRole,
  CLIENT_ONBOARDING_STEPS,
  type ClientOnboardingStep,
  WALLET_STATES,
  type WalletState,
  WALLET_ENTRY_KINDS,
  type WalletEntryKind,
  BROADCAST_STATUSES,
  type BroadcastStatus,
  MSG_DIRECTIONS,
  type MsgDirection,
  CHAT_KINDS,
  type ChatKind,
  EVENT_TYPES,
  type EventType,
  NOTIFICATION_KINDS,
  type NotificationKind,
  NOTIFICATION_SEVERITIES,
  type NotificationSeverity,
  TOPUP_STATUSES,
  type TopupStatus,
  CONTACT_SOURCES,
  type ContactSource,
  CONTACT_OPT_OUT_STATES,
  type ContactOptOutState,
  CONTACT_IMPORT_STATUSES,
  type ContactImportStatus,
  CONSENT_BASES,
  type ConsentBasis,
  BROADCAST_RECIPIENT_STATUSES,
  type BroadcastRecipientStatus,
  STAFF_ROLES,
  type StaffRole,
  IMPERSONATION_SCOPES,
  type ImpersonationScope,
} from './enums/index.js';
