/**
 * contacts-exports.ts (P20 Unit U6, step 5/7) - the contacts + contact-
 * imports re-export block split out of `index.ts` (that barrel sat at
 * exactly 300/300 lines - adding the new `contact-imports.js` export block
 * would have breached the `max-lines: 300` cap in `core-invariants.md`).
 * Sibling-module split, same idiom as `packages/domain/src/enums-exports.ts`
 * - never trim a contract comment to make room, split instead.
 */
export {
  contactSourceSchema,
  type ContactSourceContract,
  contactOptOutStateSchema,
  type ContactOptOutStateContract,
  consentBasisSchema,
  type ConsentBasisContract,
  addressingModeSchema,
  type AddressingModeContract,
  contactTagRefSchema,
  type ContactTagRef,
  contactItemSchema,
  type ContactItem,
  contactAttrsSchema,
  type ContactAttrsInput,
  createContactInputSchema,
  type CreateContactInput,
  createContactOutputSchema,
  type CreateContactOutput,
  createContactContract,
  updateContactInputSchema,
  type UpdateContactInput,
  updateContactOutputSchema,
  type UpdateContactOutput,
  updateContactContract,
  getContactInputSchema,
  type GetContactInput,
  getContactOutputSchema,
  type GetContactOutput,
  getContactContract,
  listContactsInputSchema,
  type ListContactsInput,
  listContactsOutputSchema,
  type ListContactsOutput,
  listContactsContract,
  setContactTagsInputSchema,
  type SetContactTagsInput,
  setContactTagsOutputSchema,
  type SetContactTagsOutput,
  setContactTagsContract,
  contactTagItemSchema,
  type ContactTagItem,
  createContactTagInputSchema,
  type CreateContactTagInput,
  createContactTagOutputSchema,
  type CreateContactTagOutput,
  createContactTagContract,
  listContactTagsOutputSchema,
  type ListContactTagsOutput,
  listContactTagsContract,
  patchContactTagInputSchema,
  type PatchContactTagInput,
  patchContactTagOutputSchema,
  type PatchContactTagOutput,
  patchContactTagContract,
  deleteContactTagInputSchema,
  type DeleteContactTagInput,
  deleteContactTagOutputSchema,
  type DeleteContactTagOutput,
  deleteContactTagContract,
  contactsContract,
} from './contacts.js';

export * from './contact-imports.js';
