/** @wp/contracts - Zod route/input/output schemas, error codes, and typed route contracts (shared by every frontend and backend; no Node builtins). */
export const packageName = '@wp/contracts' as const;

export {
  ERROR_CODES,
  ERROR_CODE_TO_HTTP_STATUS,
  errorCodeSchema,
  errorBodySchema,
  type ErrorCode,
  type ErrorBody,
} from './errors.js';

export {
  metaSchema,
  successEnvelope,
  errorEnvelopeSchema,
  paginationInputSchema,
  type Meta,
  type SuccessEnvelope,
  type ErrorEnvelope,
  type PaginationInput,
} from './envelope.js';

export { healthPingContract, appContract, type AppContract } from './router.js';

export {
  fullNameSchema,
  companyNameSchema,
  emailSchema,
  phoneE164Schema,
  passwordSchema,
  signupInputSchema,
  signupOutputSchema,
  signupContract,
  verifyEmailInputSchema,
  verifyEmailOutputSchema,
  verifyEmailContract,
  loginInputSchema,
  authenticatedResultSchema,
  mfaRequiredResultSchema,
  loginResultSchema,
  loginOutputSchema,
  loginContract,
  totpVerifyInputSchema,
  totpVerifyOutputSchema,
  totpVerifyContract,
  totpRecoveryInputSchema,
  totpRecoveryOutputSchema,
  totpRecoveryContract,
  totpEnrolOutputSchema,
  totpEnrolContract,
  totpEnrolConfirmInputSchema,
  totpEnrolConfirmOutputSchema,
  totpEnrolConfirmContract,
  refreshOutputSchema,
  refreshContract,
  logoutOutputSchema,
  logoutContract,
  meOutputSchema,
  meContract,
  authContract,
} from './auth.js';

export {
  onboardingStepSchema,
  type OnboardingStep,
  timezoneSchema,
  onboardingStatusOutputSchema,
  getOnboardingContract,
  setTimezoneInputSchema,
  setTimezoneOutputSchema,
  setTimezoneContract,
  setPacingProfileInputSchema,
  setPacingProfileOutputSchema,
  setPacingProfileContract,
  setConsentInputSchema,
  setConsentOutputSchema,
  setConsentContract,
  onboardingContract,
} from './onboarding.js';

export {
  realtimeEventSchema,
  type RealtimeEvent,
  REALTIME_EVENT_TYPES,
  type RealtimeEventType,
  realtimeFrameSchema,
  type RealtimeFrame,
  batchFrameSchema,
  type BatchFrame,
  realtimeEventsContract,
  realtimeContract,
} from './app/realtime.js';

export {
  linkStateSchema,
  type LinkStateContract,
  healthStateSchema,
  type HealthStateContract,
  desiredStateSchema,
  type DesiredStateContract,
  createInstanceInputSchema,
  createInstanceOutputSchema,
  createInstanceContract,
  linkInstanceInputSchema,
  linkInstanceOutputSchema,
  linkInstanceContract,
  refreshLinkOutputSchema,
  refreshLinkContract,
  linkStatusOutputSchema,
  linkStatusContract,
  onlineHolderSchema,
  onlineInstanceOutputSchema,
  noFreeSlotDetailsSchema,
  onlineInstanceContract,
  parkInstanceOutputSchema,
  parkInstanceContract,
  resumeInstanceInputSchema,
  resumeInstanceOutputSchema,
  resumeInstanceContract,
  deleteInstanceOutputSchema,
  deleteInstanceContract,
  instancesContract,
} from './instances.js';

export {
  recipientSchema,
  messageKindSchema,
  type MessageKindContract,
  messagePrioritySchema,
  MAX_PAYLOAD_BYTES,
  textPayloadSchema,
  imagePayloadSchema,
  documentPayloadSchema,
  createMessageHeadersSchema,
  type CreateMessageHeaders,
  createMessageInputSchema,
  type CreateMessageInput,
  createMessageOutputSchema,
  type CreateMessageOutput,
  createMessageContract,
  unresolvedActionHeadersSchema,
  type UnresolvedActionHeaders,
  retryUnresolvedOutputSchema,
  type RetryUnresolvedOutput,
  discardUnresolvedOutputSchema,
  type DiscardUnresolvedOutput,
  retryUnresolvedContract,
  discardUnresolvedContract,
  messagesContract,
} from './messages.js';

export {
  ackFanoutInputSchema,
  type AckFanoutInput,
  ackFanoutOutputSchema,
  type AckFanoutOutput,
  ackFanoutContract,
  pendingFanoutAckItemSchema,
  pendingFanoutAcksOutputSchema,
  type PendingFanoutAcksOutput,
  pendingFanoutAcksContract,
  pacingContract,
} from './pacing.js';

export {
  WEBHOOK_EVENT_TYPES,
  type WebhookEventType,
  createWebhookEndpointInputSchema,
  type CreateWebhookEndpointInput,
  createWebhookEndpointOutputSchema,
  type CreateWebhookEndpointOutput,
  createWebhookEndpointContract,
  patchWebhookEndpointInputSchema,
  type PatchWebhookEndpointInput,
  patchWebhookEndpointOutputSchema,
  type PatchWebhookEndpointOutput,
  patchWebhookEndpointContract,
  listWebhookEndpointsInputSchema,
  type ListWebhookEndpointsInput,
  listWebhookEndpointsOutputSchema,
  type ListWebhookEndpointsOutput,
  listWebhookEndpointsContract,
  deleteWebhookEndpointInputSchema,
  type DeleteWebhookEndpointInput,
  deleteWebhookEndpointOutputSchema,
  type DeleteWebhookEndpointOutput,
  deleteWebhookEndpointContract,
  testWebhookEndpointInputSchema,
  type TestWebhookEndpointInput,
  testWebhookEndpointOutputSchema,
  type TestWebhookEndpointOutput,
  testWebhookEndpointContract,
  webhooksContract,
} from './app/webhooks.js';

export {
  createApiKeyInputSchema,
  type CreateApiKeyInput,
  createApiKeyOutputSchema,
  type CreateApiKeyOutput,
  createApiKeyContract,
  listApiKeysOutputSchema,
  type ListApiKeysOutput,
  listApiKeysContract,
  revokeApiKeyInputSchema,
  type RevokeApiKeyInput,
  revokeApiKeyOutputSchema,
  type RevokeApiKeyOutput,
  revokeApiKeyContract,
  apiKeysContract,
} from './app/api-keys.js';

export {
  dashboardSummaryDataSchema,
  type DashboardSummaryData,
  dashboardSummaryOutputSchema,
  type DashboardSummaryOutput,
  dashboardSummaryContract,
  dashboardContract,
} from './app/dashboard.js';

export {
  notificationKindSchema,
  notificationSeveritySchema,
  listNotificationsInputSchema,
  type ListNotificationsInput,
  listNotificationsItemSchema,
  type ListNotificationsItem,
  listNotificationsOutputSchema,
  type ListNotificationsOutput,
  listNotificationsContract,
  unreadCountOutputSchema,
  type UnreadCountOutput,
  unreadCountContract,
  markReadOutputSchema,
  type MarkReadOutput,
  markReadContract,
  markAllReadOutputSchema,
  type MarkAllReadOutput,
  markAllReadContract,
  notificationsContract,
} from './notifications.js';

export {
  instanceCardDataSchema,
  type InstanceCardData,
  instanceCardOutputSchema,
  type InstanceCardOutput,
  instanceCardContract,
  healthSignalEntrySchema,
  type HealthSignalEntry,
  healthTimelineEntrySchema,
  healthWhyDataSchema,
  type HealthWhyData,
  healthWhyOutputSchema,
  type HealthWhyOutput,
  healthWhyContract,
  instanceCardContractGroup,
} from './instance-card.js';

export {
  walletStateSchema,
  type WalletStateContract,
  walletSummaryDataSchema,
  type WalletSummaryData,
  walletSummaryOutputSchema,
  type WalletSummaryOutput,
  walletSummaryContract,
  topupRequestStatusSchema,
  type TopupRequestStatus,
  createTopupRequestInputSchema,
  type CreateTopupRequestInput,
  topupRequestItemSchema,
  type TopupRequestItem,
  createTopupRequestOutputSchema,
  type CreateTopupRequestOutput,
  createTopupRequestContract,
  listTopupRequestsInputSchema,
  type ListTopupRequestsInput,
  listTopupRequestsOutputSchema,
  type ListTopupRequestsOutput,
  listTopupRequestsContract,
  queueStatusOutputSchema,
  type QueueStatusOutput,
  queueStatusContract,
  walletContract,
} from './app/wallet.js';

// 300-line cap split (see contacts-exports.ts / broadcasts-exports.ts / groups-exports.ts):
export * from './contacts-exports.js';
export * from './broadcasts-exports.js';
export * from './app/groups-exports.js';
export * from './internal/index.js';
export * from './app/media-exports.js';
// P28 U4: the whole /admin/v1 staff surface (adminContract) - Unit U6's
// admin frontend consumes these; ONE line here, everything else in admin/.
export * from './admin/index.js';
export * from './auth-password.js';
