import type { MetricInventoryEntry } from './metric-inventory.js';

/**
 * metric-inventory-core-n-r.ts (P25 unit U1a) - part of `CORE_METRIC_INVENTORY`
 * (names `wp_oldest_queued_seconds_max` through `wp_reconcile_ambiguous_total`),
 * split out of `metric-inventory.ts` purely to stay under the `max-lines: 300`
 * cap - see that file's header for the full rationale. Data-only,
 * alphabetically split; no behavioural difference from one big array.
 */
export const CORE_METRIC_INVENTORY_N_R: readonly MetricInventoryEntry[] = Object.freeze([
  {
    name: 'wp_oldest_queued_seconds_max',
    type: 'gauge',
    labels: [],
    module: 'app/backend/src/engine/queue/metrics.ts',
    alerts: true,
    help: 'Fleet-wide oldest queued job age in seconds (aggregate, no instance_id label)',
  },
  {
    name: 'wp_optout_cancelled_jobs_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/engine/queue/metrics.ts',
    alerts: false,
    help: 'Jobs disposed by the guard pipeline specifically for OPT_OUT',
  },
  {
    name: 'wp_optout_detected_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/modules/inbound/metrics.ts',
    alerts: false,
    help: 'Attributed inbound STOP keyword matches that wrote an opt_outs row',
  },
  {
    name: 'wp_optout_mirror_drift_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/platform/metrics/contacts.ts',
    alerts: false,
    help: 'Count of contacts.opt_out_state mirror drift corrections against the opt_outs authority',
  },
  {
    name: 'wp_optout_unattributable_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/modules/inbound/metrics.ts',
    alerts: false,
    help: 'Inbound opt-out keyword matches from a sender with no resolvable E.164 (never mis-attributed to a guessed contact)',
  },
  {
    name: 'wp_outbox_depth',
    type: 'gauge',
    labels: [],
    module: 'app/backend/src/platform/metrics/relay-metrics.ts',
    alerts: true,
    help: 'Unpublished outbox_events row count',
  },
  {
    name: 'wp_outbox_dropped_total',
    type: 'counter',
    labels: ['topic_class'],
    module: 'app/backend/src/platform/metrics/relay-metrics.ts',
    alerts: false,
    help: 'Outbox rows silently dropped under backpressure, by topic_class',
  },
  {
    name: 'wp_outbox_events_published_total',
    type: 'counter',
    labels: ['fanout'],
    module: 'app/backend/src/platform/metrics/relay-metrics.ts',
    alerts: true,
    help: 'Outbox events published, by fanout',
  },
  {
    name: 'wp_outbox_poison_total',
    type: 'counter',
    labels: ['topic_class'],
    module: 'app/backend/src/platform/metrics/relay-metrics.ts',
    alerts: false,
    help: 'Outbox rows quarantined after repeatedly failing to parse as a valid event, by topic_class',
  },
  {
    name: 'wp_outbox_publish_lag_seconds',
    type: 'histogram',
    labels: [],
    module: 'app/backend/src/platform/metrics/relay-metrics.ts',
    alerts: false,
    help: 'Age (seconds) of the oldest row in a drain tick claimed batch',
  },
  {
    name: 'wp_pacing_band_flaps_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/modules/pacing/health/metrics.ts',
    alerts: true,
    help: 'Flap-suppressed band loosenings (bands.ts suppressedByFlap)',
  },
  {
    name: 'wp_pacing_deferrals_total',
    type: 'counter',
    labels: ['reason'],
    module: 'app/backend/src/engine/pacing/metrics.ts',
    alerts: false,
    help: 'Pacing reserve denials, by reason - a deferral (requeue), never a job failure (label name: reason)',
  },
  {
    name: 'wp_pacing_denies_total',
    type: 'counter',
    labels: ['reason'],
    module: 'app/backend/src/engine/pacing/metrics.ts',
    alerts: false,
    help: 'Terminal pacing refusals, by reason - reserved for a future hard-deny path (label name: reason)',
  },
  {
    name: 'wp_pacing_reserve_seconds',
    type: 'histogram',
    labels: [],
    module: 'app/backend/src/engine/pacing/metrics.ts',
    alerts: false,
    help: 'Wall time of reserve() round trips (claim + reserve, in seconds)',
  },
  {
    name: 'wp_queue_depth_total',
    type: 'gauge',
    labels: [],
    module: 'app/backend/src/engine/queue/metrics.ts',
    alerts: false,
    help: 'Fleet-wide queued message_jobs count (aggregate, no instance_id label)',
  },
  {
    name: 'wp_reaper_repairs_total',
    type: 'counter',
    labels: ['result'],
    module: 'app/backend/src/engine/queue/metrics.ts',
    alerts: false,
    help: 'Lease-expiry repairs made by the reaper, by outcome (label name: result)',
  },
  {
    name: 'wp_receipt_unmatched_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/modules/inbound/metrics.ts',
    alerts: false,
    help: 'Delivery receipts whose wa_msg_id matched no resolved outbound message_wa_ids row (expected for not-yet-acked sends; dropped, not dead-lettered)',
  },
  {
    name: 'wp_receipts_total',
    type: 'counter',
    labels: ['event_type'],
    module: 'app/backend/src/modules/inbound/metrics.ts',
    alerts: false,
    help: 'Delivery receipts written to delivery_events, by event type (delivered, read, failed)',
  },
  {
    name: 'wp_reconcile_ambiguous_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/engine/queue/metrics.ts',
    alerts: true,
    help: 'Echo reconciler runs where >1 in-flight attempt shared a content hash and none was resolved',
  },
]);
