import type { MetricInventoryEntry } from './metric-inventory.js';
import { ADMIN_METRIC_INVENTORY } from './metric-inventory-admin.js';

/**
 * metric-inventory-core-a-m.ts (P25 unit U1a) - first half (names `wp_admin_*`
 * through `wp_notify_deduped_total`) of `CORE_METRIC_INVENTORY`, split out of
 * `metric-inventory.ts` purely to stay under the `max-lines: 300` cap - see
 * that file's header for the full rationale and naming-reconciliation notes.
 * This is data-only, alphabetically split; no behavioural difference from
 * one big array.
 *
 * P28 U4: the `wp_admin_*` entries (admin-backend's own registry) are spread
 * in from `metric-inventory-admin.ts` rather than inlined - this file sits
 * at 268/300 lines and two full entries would breach the cap. Same
 * sibling-module split idiom, and it keeps the alphabetical ordering
 * (`wp_admin_*` precedes `wp_auth_*`).
 */
export const CORE_METRIC_INVENTORY_A_M: readonly MetricInventoryEntry[] = Object.freeze([
  ...ADMIN_METRIC_INVENTORY,
  {
    name: 'wp_auth_state_field_evicted_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/platform/metrics/signal-metrics.ts',
    alerts: false,
    help: 'REBUILDABLE-tier (cache-only) redis-sig fields trimmed at the per-instance field cap',
  },
  {
    name: 'wp_box_rss_bytes',
    type: 'gauge',
    labels: [],
    module: 'app/backend/src/engine/fleet/metrics.ts',
    alerts: false,
    help: 'Host-level used memory (os.totalmem() - os.freemem()), in bytes',
  },
  {
    name: 'wp_broadcast_expansion_lag_seconds',
    type: 'histogram',
    labels: [],
    module: 'app/backend/src/platform/metrics/broadcast-metrics.ts',
    alerts: true,
    help: 'Seconds between a campaign snapshot_done_at and an expansion batch commit',
  },
  {
    name: 'wp_broadcast_recipients_total',
    type: 'counter',
    labels: ['status'],
    module: 'app/backend/src/platform/metrics/broadcast-metrics.ts',
    alerts: false,
    help: 'campaign_recipients rows entering a status, by status',
  },
  {
    name: 'wp_claim_lost_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/engine/queue/metrics.ts',
    alerts: false,
    help: 'Job outcome writes that found zero matching rows - another worker owned the job by then',
  },
  {
    name: 'wp_connect_bucket_wait_seconds',
    type: 'histogram',
    labels: [],
    module: 'app/backend/src/engine/fleet/metrics.ts',
    alerts: false,
    help: 'Time a session waited in the connect-rate bucket before being allowed to link, in seconds',
  },
  {
    name: 'wp_contact_import_rows_total',
    type: 'counter',
    labels: ['result'],
    module: 'app/backend/src/platform/metrics/contacts.ts',
    alerts: false,
    help: 'Contact import per-record outcomes, by result',
  },
  {
    name: 'wp_contacts_imported_total',
    type: 'counter',
    labels: ['result'],
    module: 'app/backend/src/platform/metrics/contacts.ts',
    alerts: false,
    help: 'Contact import job outcomes, by result',
  },
  {
    name: 'wp_content_guard_trips_total',
    type: 'counter',
    labels: ['reason'],
    module: 'app/backend/src/engine/queue/metrics.ts',
    alerts: false,
    help: 'Content-guard pipeline trips (terminal disposal or deferral), by reason (label name: reason)',
  },
  {
    name: 'wp_echo_capture_failed_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/engine/queue/metrics.ts',
    alerts: false,
    help: 'fromMe echoes that could not be recorded (missing id/content/jid, or a DB error)',
  },
  {
    name: 'wp_fence_regression_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/platform/metrics/lease-metrics.ts',
    alerts: true,
    help: 'Minted fences that were not strictly greater than the last fence this process saw for the instance (should never fire)',
  },
  {
    name: 'wp_fleet_capacity_headroom',
    type: 'gauge',
    labels: [],
    module: 'app/backend/src/platform/metrics/discovery-metrics.ts',
    alerts: true,
    help: 'Sum of published worker caps minus the desired-online instance count',
  },
  {
    name: 'wp_group_sends_total',
    type: 'counter',
    labels: ['result'],
    module: 'app/backend/src/platform/metrics/groups-metrics.ts',
    alerts: false,
    help: 'Group message send results, by result (sent | failed | group_forbidden)',
  },
  {
    name: 'wp_group_sync_seconds',
    type: 'histogram',
    labels: [],
    module: 'app/backend/src/platform/metrics/groups-metrics.ts',
    alerts: false,
    help: 'Seconds taken by one wa_groups sync (groupFetchAllParticipating) for one instance',
  },
  {
    name: 'wp_hard_signal_pauses_total',
    type: 'counter',
    labels: ['signal'],
    module: 'app/backend/src/modules/pacing/health/metrics.ts',
    alerts: true,
    help: 'Applied hard-signal pauses, by pause reason (label name: signal)',
  },
  {
    name: 'wp_health_band_changes_total',
    type: 'counter',
    labels: ['from', 'to'],
    module: 'app/backend/src/modules/pacing/health/metrics.ts',
    alerts: false,
    help: 'Applied health-band changes, by from/to band (label names: from, to)',
  },
  {
    name: 'wp_health_score',
    type: 'gauge',
    labels: [],
    module: 'app/backend/src/modules/pacing/health/metrics.ts',
    alerts: false,
    help: 'Minimum health score across instances evaluated in the most recent evaluator-loop pass (no labels - per-instance scores live in PostgreSQL)',
  },
  {
    name: 'wp_inbound_admission_fail_open_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/modules/inbound/metrics.ts',
    alerts: false,
    help: 'Inbound admission checks that failed open (processed anyway) because the Redis bucket was unavailable or timed out',
  },
  {
    name: 'wp_inbound_dead_letters_total',
    type: 'counter',
    labels: ['error_class'],
    module: 'app/backend/src/modules/inbound/metrics.ts',
    alerts: true,
    help: 'Inbound events whose handler threw and were recorded as dead letters, by bounded error class',
  },
  {
    name: 'wp_inbound_events_total',
    type: 'counter',
    labels: ['kind'],
    module: 'app/backend/src/modules/inbound/metrics.ts',
    alerts: true,
    help: 'Inbound socket events seen by the dispatcher, by kind (echo, message, receipt, ignored)',
  },
  {
    name: 'wp_inbound_limit_fallback_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/modules/inbound/metrics.ts',
    alerts: false,
    help: 'A resolved per-instance inbound limit that was not a positive integer and was replaced by the platform default',
  },
  {
    name: 'wp_inbound_overflow_total',
    type: 'counter',
    labels: ['kind'],
    module: 'app/backend/src/modules/inbound/metrics.ts',
    alerts: false,
    help: 'Inbound socket events dropped by the per-worker in-flight limiter (slots and pending queue both full), by kind',
  },
  {
    name: 'wp_inbound_shed_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/modules/inbound/metrics.ts',
    alerts: true,
    help: 'Inbound message events dropped above the per-instance admission ceiling, before any processing',
  },
  {
    name: 'wp_instance_health_state',
    type: 'gauge',
    labels: ['instance_id', 'client_id'],
    module: 'app/backend/src/modules/pacing/health/metrics.ts',
    alerts: true,
    help: 'Per-instance whatsapp_instances.health_state, numerically encoded (see HEALTH_STATE_GAUGE_VALUES; label names: instance_id, client_id)',
  },
  {
    name: 'wp_instances_unowned',
    type: 'gauge',
    labels: [],
    module: 'app/backend/src/platform/metrics/discovery-metrics.ts',
    alerts: true,
    help: 'Count of desired-online, non-deleted instances with no live lease',
  },
  {
    name: 'wp_lease_heartbeat_ticks_skipped_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/platform/metrics/lease-metrics.ts',
    alerts: false,
    help: 'Heartbeat ticks skipped because a previous tick was still in flight (re-entrancy guard)',
  },
  {
    name: 'wp_lease_lost_total',
    type: 'counter',
    labels: ['cause'],
    module: 'app/backend/src/platform/metrics/lease-metrics.ts',
    alerts: false,
    help: 'Session leases self-fenced (lost), by cause',
  },
  {
    name: 'wp_lease_takeovers_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/platform/metrics/lease-metrics.ts',
    alerts: true,
    help: 'Session lease takeovers - a mint replaced a different previous owner',
  },
  {
    name: 'wp_notification_email_failures_total',
    type: 'counter',
    labels: ['kind'],
    module: 'app/backend/src/platform/metrics/notification-metrics.ts',
    alerts: false,
    help: 'Notification email sends that failed (SMTP or any per-row error), by kind',
  },
  {
    name: 'wp_notification_emails_suppressed_total',
    type: 'counter',
    labels: ['kind'],
    module: 'app/backend/src/platform/metrics/notification-metrics.ts',
    alerts: false,
    help: 'Notification emails suppressed by the per-client hourly cap, by kind',
  },
  {
    name: 'wp_notifications_total',
    type: 'counter',
    labels: ['kind', 'channel'],
    module: 'app/backend/src/platform/metrics/notification-metrics.ts',
    alerts: false,
    help: 'Notification outbox fan-out rows written, by kind and channel',
  },
  {
    name: 'wp_notify_deduped_total',
    type: 'counter',
    labels: ['kind'],
    module: 'app/backend/src/platform/metrics/notification-metrics.ts',
    alerts: false,
    help: 'notify() calls suppressed by the dedupe unique constraint, by kind',
  },
]);
