import type { MetricInventoryEntry } from './metric-inventory.js';

/**
 * metric-inventory-core-s-z.ts (P25 unit U1a) - last part of
 * `CORE_METRIC_INVENTORY` (names `wp_redis_sig_field_cap_reached_total`
 * through `wp_worker_sheds_total`), split out of `metric-inventory.ts` purely
 * to stay under the `max-lines: 300` cap - see that file's header for the
 * full rationale. Data-only, alphabetically split; no behavioural difference
 * from one big array.
 */
export const CORE_METRIC_INVENTORY_S_Z: readonly MetricInventoryEntry[] = Object.freeze([
  {
    name: 'wp_redis_sig_field_cap_reached_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/platform/metrics/signal-metrics.ts',
    alerts: false,
    help: 'SIGNAL-tier redis-sig writes at/beyond the per-instance field cap (alarm only, write always allowed)',
  },
  {
    name: 'wp_safety_poll_claims_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/engine/queue/metrics.ts',
    alerts: false,
    help: 'Claim attempts triggered by the mandatory safety-poll timer rather than a wake or the per-instance eligibility timer',
  },
  {
    name: 'wp_send_attempts_total',
    type: 'counter',
    labels: ['result'],
    module: 'app/backend/src/engine/queue/metrics.ts',
    alerts: true,
    help: 'Send attempts by outcome',
  },
  {
    name: 'wp_send_duration_seconds',
    type: 'histogram',
    labels: [],
    module: 'app/backend/src/engine/queue/metrics.ts',
    alerts: false,
    help: 'Wall time from dispatch start to result resolution, per attempt, in seconds',
  },
  {
    name: 'wp_send_loop_iteration_errors_total',
    type: 'counter',
    labels: ['reason'],
    module: 'app/backend/src/engine/queue/metrics.ts',
    alerts: false,
    help: 'Send-loop iterations whose runOneIteration call rejected, by the rejecting error name (label name: reason)',
  },
  {
    name: 'wp_session_measured_mb',
    type: 'gauge',
    labels: [],
    module: 'app/backend/src/engine/fleet/metrics.ts',
    alerts: false,
    help: 'Accepted 24h-trimmed-mean measured per-session RSS footprint, in MB (session-cost-feedback loop)',
  },
  {
    name: 'wp_session_rss_bytes_est',
    type: 'gauge',
    labels: [],
    module: 'app/backend/src/engine/fleet/metrics.ts',
    alerts: true,
    help: 'Estimated per-session RSS footprint (slope of RSS vs session count), in bytes',
  },
  {
    name: 'wp_shed_no_taker_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/engine/fleet/shed.ts',
    alerts: true,
    help: 'Shed instances not re-grabbed by another worker within two scan cycles',
  },
  {
    name: 'wp_signal_decrypt_failure_total',
    type: 'counter',
    labels: ['cause'],
    module: 'app/backend/src/platform/metrics/signal-metrics.ts',
    alerts: true,
    help: 'Auth-state decrypt (open) failures, by cause',
  },
  {
    name: 'wp_signal_keystore_evicted_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/platform/metrics/signal-metrics.ts',
    alerts: false,
    help: 'Bounded Signal key-store LRU evictions past the tracked-devices cap',
  },
  {
    name: 'wp_signal_keystore_hit_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/platform/metrics/signal-metrics.ts',
    alerts: false,
    help: 'Bounded Signal key-store in-memory cache hits',
  },
  {
    name: 'wp_signal_keystore_miss_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/platform/metrics/signal-metrics.ts',
    alerts: false,
    help: 'Bounded Signal key-store in-memory cache misses (cold, evicted, or TTL-expired)',
  },
  {
    name: 'wp_sse_authz_tick_errors_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/modules/realtime/metrics.ts',
    alerts: false,
    help: 'SSE re-authorisation tick query failures',
  },
  {
    name: 'wp_sse_coalesced_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/platform/metrics/relay-metrics.ts',
    alerts: false,
    help: 'Outbox rows suppressed (folded into a newer winner) by the coalescer',
  },
  {
    name: 'wp_sse_connections',
    type: 'gauge',
    labels: [],
    module: 'app/backend/src/modules/realtime/metrics.ts',
    alerts: false,
    help: 'current open SSE connections',
  },
  {
    name: 'wp_sse_drops_total',
    type: 'counter',
    labels: ['reason'],
    module: 'app/backend/src/modules/realtime/metrics.ts',
    alerts: false,
    help: 'SSE connections dropped, by reason',
  },
  {
    name: 'wp_sse_subscriptions_refused_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/modules/realtime/metrics.ts',
    alerts: false,
    help: 'SSE instance-channel subscription requests refused (not owned by caller)',
  },
  {
    name: 'wp_staff_mutations_total',
    type: 'counter',
    labels: ['action'],
    module: 'app/backend/src/platform/metrics/staff-metrics.ts',
    alerts: false,
    help: 'Staff mutations that committed via withStaffMutation, by action',
  },
  {
    name: 'wp_stranded_epoch_jobs',
    type: 'gauge',
    labels: [],
    module: 'app/backend/src/platform/metrics/broadcast-metrics.ts',
    alerts: true,
    help: 'Fleet-wide count of message_jobs rows blocked_needs_review with unresolved_reason session_epoch_advanced',
  },
  {
    name: 'wp_unresolved_jobs_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/engine/queue/metrics.ts',
    alerts: true,
    help: 'Jobs moved to needs_reconcile by the reaper, pending human/reconciler resolution',
  },
  {
    name: 'wp_wake_received_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/engine/queue/metrics.ts',
    alerts: false,
    help: 'Wake pub/sub messages actually received on a subscribed instance channel',
  },
  {
    name: 'wp_wallet_clients_empty',
    type: 'gauge',
    labels: [],
    module: 'app/backend/src/platform/metrics/wallet-metrics.ts',
    alerts: false,
    help: 'Count of clients whose wallet is currently in the empty state',
  },
  {
    name: 'wp_wallet_debits_total',
    type: 'counter',
    labels: ['price_key'],
    module: 'app/backend/src/platform/metrics/wallet-metrics.ts',
    alerts: false,
    help: 'Wallet debit events, by price key',
  },
  {
    name: 'wp_wallet_drift_minor',
    type: 'gauge',
    labels: [],
    module: 'app/backend/src/platform/metrics/wallet-metrics.ts',
    alerts: true,
    help: 'Checkpoint-vs-ledger wallet balance drift, in minor units (paise)',
  },
  {
    name: 'wp_wallet_refunds_total',
    type: 'counter',
    labels: ['reason'],
    module: 'app/backend/src/platform/metrics/wallet-metrics.ts',
    alerts: false,
    help: 'Wallet refund events, by reason',
  },
  {
    name: 'wp_wallet_topups_total',
    type: 'counter',
    labels: ['status'],
    module: 'app/backend/src/platform/metrics/wallet-metrics.ts',
    alerts: false,
    help: 'Tenant top-up requests, by status',
  },
  {
    name: 'wp_warmup_tier_changes_total',
    type: 'counter',
    labels: ['result'],
    module: 'app/backend/src/engine/pacing/metrics.ts',
    alerts: false,
    help: 'Warm-up ladder tier changes applied by the pacing evaluator (label name: result, not direction - see module doc)',
  },
  {
    name: 'wp_worker_eventloop_lag_p99',
    type: 'gauge',
    labels: [],
    module: 'app/backend/src/engine/fleet/metrics.ts',
    alerts: true,
    help: 'p99 event-loop delay in milliseconds for this worker',
  },
  {
    name: 'wp_worker_session_cap',
    type: 'gauge',
    labels: [],
    module: 'app/backend/src/engine/fleet/metrics.ts',
    alerts: true,
    help: "This worker's derived session cap (deriveSessionCap output)",
  },
  {
    name: 'wp_worker_sessions',
    type: 'gauge',
    labels: [],
    module: 'app/backend/src/engine/fleet/metrics.ts',
    alerts: true,
    help: 'Sessions currently held by this worker',
  },
  {
    name: 'wp_worker_sheds_total',
    type: 'counter',
    labels: [],
    module: 'app/backend/src/engine/fleet/shed.ts',
    alerts: false,
    help: 'Total sessions shed by this worker',
  },
]);
