/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as ImpersonateRouteImport } from './routes/impersonate'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TotpRouteImport } from './routes/totp'
import { Route as VerifyEmailRouteImport } from './routes/verify-email'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedContactsRouteImport } from './routes/_authed/contacts'
import { Route as AuthedGroupsRouteImport } from './routes/_authed/groups'
import { Route as AuthedMessagesRouteImport } from './routes/_authed/messages'
import { Route as AuthedUnresolvedRouteImport } from './routes/_authed/unresolved'
import { Route as AuthedWalletRouteImport } from './routes/_authed/wallet'
import { Route as DevGalleryRouteImport } from './routes/dev.gallery'
import { Route as AuthedBroadcastsIndexRouteImport } from './routes/_authed/broadcasts.index'
import { Route as AuthedBroadcastsIdRouteImport } from './routes/_authed/broadcasts.$id'
import { Route as AuthedBroadcastsNewRouteImport } from './routes/_authed/broadcasts.new'
import { Route as AuthedInstancesIndexRouteImport } from './routes/_authed/instances.index'
import { Route as AuthedInstancesIdRouteImport } from './routes/_authed/instances.$id'
import { Route as AuthedSettingsApiKeysRouteImport } from './routes/_authed/settings.api-keys'
import { Route as AuthedSettingsSecurityRouteImport } from './routes/_authed/settings.security'
import { Route as AuthedSettingsWebhooksRouteImport } from './routes/_authed/settings.webhooks'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpersonateRoute = ImpersonateRouteImport.update({
  id: '/impersonate',
  path: '/impersonate',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TotpRoute = TotpRouteImport.update({
  id: '/totp',
  path: '/totp',
  getParentRoute: () => rootRouteImport,
} as any)
const VerifyEmailRoute = VerifyEmailRouteImport.update({
  id: '/verify-email',
  path: '/verify-email',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedContactsRoute = AuthedContactsRouteImport.update({
  id: '/contacts',
  path: '/contacts',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedGroupsRoute = AuthedGroupsRouteImport.update({
  id: '/groups',
  path: '/groups',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedMessagesRoute = AuthedMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedUnresolvedRoute = AuthedUnresolvedRouteImport.update({
  id: '/unresolved',
  path: '/unresolved',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedWalletRoute = AuthedWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => AuthedRoute,
} as any)
const DevGalleryRoute = DevGalleryRouteImport.update({
  id: '/dev/gallery',
  path: '/dev/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedBroadcastsIndexRoute = AuthedBroadcastsIndexRouteImport.update({
  id: '/broadcasts/',
  path: '/broadcasts/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBroadcastsIdRoute = AuthedBroadcastsIdRouteImport.update({
  id: '/broadcasts/$id',
  path: '/broadcasts/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedBroadcastsNewRoute = AuthedBroadcastsNewRouteImport.update({
  id: '/broadcasts/new',
  path: '/broadcasts/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInstancesIndexRoute = AuthedInstancesIndexRouteImport.update({
  id: '/instances/',
  path: '/instances/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInstancesIdRoute = AuthedInstancesIdRouteImport.update({
  id: '/instances/$id',
  path: '/instances/$id',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsApiKeysRoute = AuthedSettingsApiKeysRouteImport.update({
  id: '/settings/api-keys',
  path: '/settings/api-keys',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsSecurityRoute = AuthedSettingsSecurityRouteImport.update({
  id: '/settings/security',
  path: '/settings/security',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedSettingsWebhooksRoute = AuthedSettingsWebhooksRouteImport.update({
  id: '/settings/webhooks',
  path: '/settings/webhooks',
  getParentRoute: () => AuthedRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/impersonate': typeof ImpersonateRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/totp': typeof TotpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/contacts': typeof AuthedContactsRoute
  '/groups': typeof AuthedGroupsRoute
  '/messages': typeof AuthedMessagesRoute
  '/unresolved': typeof AuthedUnresolvedRoute
  '/wallet': typeof AuthedWalletRoute
  '/dev/gallery': typeof DevGalleryRoute
  '/broadcasts/$id': typeof AuthedBroadcastsIdRoute
  '/broadcasts/new': typeof AuthedBroadcastsNewRoute
  '/instances/$id': typeof AuthedInstancesIdRoute
  '/settings/api-keys': typeof AuthedSettingsApiKeysRoute
  '/settings/security': typeof AuthedSettingsSecurityRoute
  '/settings/webhooks': typeof AuthedSettingsWebhooksRoute
  '/broadcasts/': typeof AuthedBroadcastsIndexRoute
  '/instances/': typeof AuthedInstancesIndexRoute
}
export interface FileRoutesByTo {
  '/forgot-password': typeof ForgotPasswordRoute
  '/impersonate': typeof ImpersonateRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/totp': typeof TotpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/contacts': typeof AuthedContactsRoute
  '/groups': typeof AuthedGroupsRoute
  '/messages': typeof AuthedMessagesRoute
  '/unresolved': typeof AuthedUnresolvedRoute
  '/wallet': typeof AuthedWalletRoute
  '/dev/gallery': typeof DevGalleryRoute
  '/': typeof AuthedIndexRoute
  '/broadcasts/$id': typeof AuthedBroadcastsIdRoute
  '/broadcasts/new': typeof AuthedBroadcastsNewRoute
  '/instances/$id': typeof AuthedInstancesIdRoute
  '/settings/api-keys': typeof AuthedSettingsApiKeysRoute
  '/settings/security': typeof AuthedSettingsSecurityRoute
  '/settings/webhooks': typeof AuthedSettingsWebhooksRoute
  '/broadcasts': typeof AuthedBroadcastsIndexRoute
  '/instances': typeof AuthedInstancesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/impersonate': typeof ImpersonateRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/totp': typeof TotpRoute
  '/verify-email': typeof VerifyEmailRoute
  '/_authed/contacts': typeof AuthedContactsRoute
  '/_authed/groups': typeof AuthedGroupsRoute
  '/_authed/messages': typeof AuthedMessagesRoute
  '/_authed/unresolved': typeof AuthedUnresolvedRoute
  '/_authed/wallet': typeof AuthedWalletRoute
  '/dev/gallery': typeof DevGalleryRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/broadcasts/$id': typeof AuthedBroadcastsIdRoute
  '/_authed/broadcasts/new': typeof AuthedBroadcastsNewRoute
  '/_authed/instances/$id': typeof AuthedInstancesIdRoute
  '/_authed/settings/api-keys': typeof AuthedSettingsApiKeysRoute
  '/_authed/settings/security': typeof AuthedSettingsSecurityRoute
  '/_authed/settings/webhooks': typeof AuthedSettingsWebhooksRoute
  '/_authed/broadcasts/': typeof AuthedBroadcastsIndexRoute
  '/_authed/instances/': typeof AuthedInstancesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/impersonate'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/totp'
    | '/verify-email'
    | '/contacts'
    | '/groups'
    | '/messages'
    | '/unresolved'
    | '/wallet'
    | '/dev/gallery'
    | '/broadcasts/$id'
    | '/broadcasts/new'
    | '/instances/$id'
    | '/settings/api-keys'
    | '/settings/security'
    | '/settings/webhooks'
    | '/broadcasts/'
    | '/instances/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/forgot-password'
    | '/impersonate'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/totp'
    | '/verify-email'
    | '/contacts'
    | '/groups'
    | '/messages'
    | '/unresolved'
    | '/wallet'
    | '/dev/gallery'
    | '/'
    | '/broadcasts/$id'
    | '/broadcasts/new'
    | '/instances/$id'
    | '/settings/api-keys'
    | '/settings/security'
    | '/settings/webhooks'
    | '/broadcasts'
    | '/instances'
  id:
    | '__root__'
    | '/_authed'
    | '/forgot-password'
    | '/impersonate'
    | '/login'
    | '/onboarding'
    | '/reset-password'
    | '/signup'
    | '/totp'
    | '/verify-email'
    | '/_authed/contacts'
    | '/_authed/groups'
    | '/_authed/messages'
    | '/_authed/unresolved'
    | '/_authed/wallet'
    | '/dev/gallery'
    | '/_authed/'
    | '/_authed/broadcasts/$id'
    | '/_authed/broadcasts/new'
    | '/_authed/instances/$id'
    | '/_authed/settings/api-keys'
    | '/_authed/settings/security'
    | '/_authed/settings/webhooks'
    | '/_authed/broadcasts/'
    | '/_authed/instances/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ImpersonateRoute: typeof ImpersonateRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  TotpRoute: typeof TotpRoute
  VerifyEmailRoute: typeof VerifyEmailRoute
  DevGalleryRoute: typeof DevGalleryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impersonate': {
      id: '/impersonate'
      path: '/impersonate'
      fullPath: '/impersonate'
      preLoaderRoute: typeof ImpersonateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/totp': {
      id: '/totp'
      path: '/totp'
      fullPath: '/totp'
      preLoaderRoute: typeof TotpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/verify-email': {
      id: '/verify-email'
      path: '/verify-email'
      fullPath: '/verify-email'
      preLoaderRoute: typeof VerifyEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/contacts': {
      id: '/_authed/contacts'
      path: '/contacts'
      fullPath: '/contacts'
      preLoaderRoute: typeof AuthedContactsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/groups': {
      id: '/_authed/groups'
      path: '/groups'
      fullPath: '/groups'
      preLoaderRoute: typeof AuthedGroupsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/messages': {
      id: '/_authed/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof AuthedMessagesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/unresolved': {
      id: '/_authed/unresolved'
      path: '/unresolved'
      fullPath: '/unresolved'
      preLoaderRoute: typeof AuthedUnresolvedRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/wallet': {
      id: '/_authed/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof AuthedWalletRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/dev/gallery': {
      id: '/dev/gallery'
      path: '/dev/gallery'
      fullPath: '/dev/gallery'
      preLoaderRoute: typeof DevGalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/broadcasts/': {
      id: '/_authed/broadcasts/'
      path: '/broadcasts'
      fullPath: '/broadcasts/'
      preLoaderRoute: typeof AuthedBroadcastsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/broadcasts/$id': {
      id: '/_authed/broadcasts/$id'
      path: '/broadcasts/$id'
      fullPath: '/broadcasts/$id'
      preLoaderRoute: typeof AuthedBroadcastsIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/broadcasts/new': {
      id: '/_authed/broadcasts/new'
      path: '/broadcasts/new'
      fullPath: '/broadcasts/new'
      preLoaderRoute: typeof AuthedBroadcastsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/instances/': {
      id: '/_authed/instances/'
      path: '/instances'
      fullPath: '/instances/'
      preLoaderRoute: typeof AuthedInstancesIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/instances/$id': {
      id: '/_authed/instances/$id'
      path: '/instances/$id'
      fullPath: '/instances/$id'
      preLoaderRoute: typeof AuthedInstancesIdRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/api-keys': {
      id: '/_authed/settings/api-keys'
      path: '/settings/api-keys'
      fullPath: '/settings/api-keys'
      preLoaderRoute: typeof AuthedSettingsApiKeysRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/security': {
      id: '/_authed/settings/security'
      path: '/settings/security'
      fullPath: '/settings/security'
      preLoaderRoute: typeof AuthedSettingsSecurityRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/settings/webhooks': {
      id: '/_authed/settings/webhooks'
      path: '/settings/webhooks'
      fullPath: '/settings/webhooks'
      preLoaderRoute: typeof AuthedSettingsWebhooksRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedContactsRoute: typeof AuthedContactsRoute
  AuthedGroupsRoute: typeof AuthedGroupsRoute
  AuthedMessagesRoute: typeof AuthedMessagesRoute
  AuthedUnresolvedRoute: typeof AuthedUnresolvedRoute
  AuthedWalletRoute: typeof AuthedWalletRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedBroadcastsIdRoute: typeof AuthedBroadcastsIdRoute
  AuthedBroadcastsNewRoute: typeof AuthedBroadcastsNewRoute
  AuthedInstancesIdRoute: typeof AuthedInstancesIdRoute
  AuthedSettingsApiKeysRoute: typeof AuthedSettingsApiKeysRoute
  AuthedSettingsSecurityRoute: typeof AuthedSettingsSecurityRoute
  AuthedSettingsWebhooksRoute: typeof AuthedSettingsWebhooksRoute
  AuthedBroadcastsIndexRoute: typeof AuthedBroadcastsIndexRoute
  AuthedInstancesIndexRoute: typeof AuthedInstancesIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedContactsRoute: AuthedContactsRoute,
  AuthedGroupsRoute: AuthedGroupsRoute,
  AuthedMessagesRoute: AuthedMessagesRoute,
  AuthedUnresolvedRoute: AuthedUnresolvedRoute,
  AuthedWalletRoute: AuthedWalletRoute,
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedBroadcastsIdRoute: AuthedBroadcastsIdRoute,
  AuthedBroadcastsNewRoute: AuthedBroadcastsNewRoute,
  AuthedInstancesIdRoute: AuthedInstancesIdRoute,
  AuthedSettingsApiKeysRoute: AuthedSettingsApiKeysRoute,
  AuthedSettingsSecurityRoute: AuthedSettingsSecurityRoute,
  AuthedSettingsWebhooksRoute: AuthedSettingsWebhooksRoute,
  AuthedBroadcastsIndexRoute: AuthedBroadcastsIndexRoute,
  AuthedInstancesIndexRoute: AuthedInstancesIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ImpersonateRoute: ImpersonateRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  TotpRoute: TotpRoute,
  VerifyEmailRoute: VerifyEmailRoute,
  DevGalleryRoute: DevGalleryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
