import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import prettier from 'prettier';
import { METRIC_INVENTORY } from '@wp/domain';
import type { MetricInventoryEntry } from '@wp/domain';
import { REPO_ROOT } from './guards/scan-config.js';

/**
 * gen-metric-manifest.ts (P25 observability-and-runbook, unit U1a) -
 * deterministically renders `packages/domain/src/obs/metric-inventory*.ts`
 * to the committed `infra/observability/metrics.generated.json`, sorted by
 * name and prettier-formatted so the output is byte-stable under
 * `pnpm run format`. Default mode writes the file; `--check` mode
 * regenerates in memory and exits 1 if the committed file differs or is
 * missing (no silent drift between the source-of-truth array and the
 * artefact operators/dashboards read).
 */

export const MANIFEST_PATH = path.join(REPO_ROOT, 'infra/observability/metrics.generated.json');
const PRETTIER_CONFIG_PATH = path.join(REPO_ROOT, 'packages/config/prettier.config.mjs');

export async function renderMetricManifest(
  inventory: readonly MetricInventoryEntry[],
): Promise<string> {
  const sorted = [...inventory].sort((a, b) => a.name.localeCompare(b.name));
  const manifest = {
    $comment:
      'GENERATED by scripts/gen-metric-manifest.ts from packages/domain/src/obs/metric-inventory*.ts - do not edit by hand',
    metrics: sorted.map((entry) => ({
      name: entry.name,
      type: entry.type,
      labels: entry.labels,
      module: entry.module,
      alerts: entry.alerts,
      help: entry.help,
    })),
  };

  const raw = JSON.stringify(manifest, null, 2);
  const resolvedConfig = await prettier.resolveConfig(PRETTIER_CONFIG_PATH);
  return prettier.format(raw, {
    ...(resolvedConfig ?? {}),
    parser: 'json',
    filepath: MANIFEST_PATH,
  });
}

async function main(): Promise<void> {
  const checkMode = process.argv.includes('--check');
  const rendered = await renderMetricManifest(METRIC_INVENTORY);

  if (!checkMode) {
    writeFileSync(MANIFEST_PATH, rendered, 'utf8');
    console.log(`gen-metric-manifest: wrote ${MANIFEST_PATH}`);
    return;
  }

  let existing: string | undefined;
  try {
    existing = readFileSync(MANIFEST_PATH, 'utf8');
  } catch {
    existing = undefined;
  }

  if (existing === undefined) {
    console.error(
      `gen-metric-manifest: ${MANIFEST_PATH} is missing - run without --check to generate it`,
    );
    process.exit(1);
  }

  if (existing !== rendered) {
    console.error(
      `gen-metric-manifest: ${MANIFEST_PATH} is stale - it disagrees with METRIC_INVENTORY. Run "tsx scripts/gen-metric-manifest.ts" and commit the result.`,
    );
    process.exit(1);
  }

  console.log('gen-metric-manifest: committed manifest matches METRIC_INVENTORY');
}

const isMain =
  process.argv[1] !== undefined && fileURLToPath(import.meta.url) === path.resolve(process.argv[1]);

if (isMain) {
  main().catch((error: unknown) => {
    console.error(error);
    process.exit(1);
  });
}
