/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as AuthedAuditRouteImport } from './routes/_authed/audit'
import { Route as AuthedClientsRouteImport } from './routes/_authed/clients'
import { Route as AuthedInstancesRouteImport } from './routes/_authed/instances'
import { Route as AuthedQueueRouteImport } from './routes/_authed/queue'
import { Route as AuthedTopupsRouteImport } from './routes/_authed/topups'
import { Route as AuthedClientsClientIdRouteImport } from './routes/_authed/clients.$clientId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedAuditRoute = AuthedAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClientsRoute = AuthedClientsRouteImport.update({
  id: '/clients',
  path: '/clients',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedInstancesRoute = AuthedInstancesRouteImport.update({
  id: '/instances',
  path: '/instances',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedQueueRoute = AuthedQueueRouteImport.update({
  id: '/queue',
  path: '/queue',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedTopupsRoute = AuthedTopupsRouteImport.update({
  id: '/topups',
  path: '/topups',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedClientsClientIdRoute = AuthedClientsClientIdRouteImport.update({
  id: '/$clientId',
  path: '/$clientId',
  getParentRoute: () => AuthedClientsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/login': typeof LoginRoute
  '/audit': typeof AuthedAuditRoute
  '/clients': typeof AuthedClientsRouteWithChildren
  '/instances': typeof AuthedInstancesRoute
  '/queue': typeof AuthedQueueRoute
  '/topups': typeof AuthedTopupsRoute
  '/clients/$clientId': typeof AuthedClientsClientIdRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/audit': typeof AuthedAuditRoute
  '/clients': typeof AuthedClientsRouteWithChildren
  '/instances': typeof AuthedInstancesRoute
  '/queue': typeof AuthedQueueRoute
  '/topups': typeof AuthedTopupsRoute
  '/': typeof AuthedIndexRoute
  '/clients/$clientId': typeof AuthedClientsClientIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/login': typeof LoginRoute
  '/_authed/audit': typeof AuthedAuditRoute
  '/_authed/clients': typeof AuthedClientsRouteWithChildren
  '/_authed/instances': typeof AuthedInstancesRoute
  '/_authed/queue': typeof AuthedQueueRoute
  '/_authed/topups': typeof AuthedTopupsRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/clients/$clientId': typeof AuthedClientsClientIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/audit'
    | '/clients'
    | '/instances'
    | '/queue'
    | '/topups'
    | '/clients/$clientId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/audit'
    | '/clients'
    | '/instances'
    | '/queue'
    | '/topups'
    | '/'
    | '/clients/$clientId'
  id:
    | '__root__'
    | '/_authed'
    | '/login'
    | '/_authed/audit'
    | '/_authed/clients'
    | '/_authed/instances'
    | '/_authed/queue'
    | '/_authed/topups'
    | '/_authed/'
    | '/_authed/clients/$clientId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/audit': {
      id: '/_authed/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuthedAuditRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients': {
      id: '/_authed/clients'
      path: '/clients'
      fullPath: '/clients'
      preLoaderRoute: typeof AuthedClientsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/instances': {
      id: '/_authed/instances'
      path: '/instances'
      fullPath: '/instances'
      preLoaderRoute: typeof AuthedInstancesRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/queue': {
      id: '/_authed/queue'
      path: '/queue'
      fullPath: '/queue'
      preLoaderRoute: typeof AuthedQueueRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/topups': {
      id: '/_authed/topups'
      path: '/topups'
      fullPath: '/topups'
      preLoaderRoute: typeof AuthedTopupsRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/clients/$clientId': {
      id: '/_authed/clients/$clientId'
      path: '/$clientId'
      fullPath: '/clients/$clientId'
      preLoaderRoute: typeof AuthedClientsClientIdRouteImport
      parentRoute: typeof AuthedClientsRoute
    }
  }
}

interface AuthedClientsRouteChildren {
  AuthedClientsClientIdRoute: typeof AuthedClientsClientIdRoute
}

const AuthedClientsRouteChildren: AuthedClientsRouteChildren = {
  AuthedClientsClientIdRoute: AuthedClientsClientIdRoute,
}

const AuthedClientsRouteWithChildren = AuthedClientsRoute._addFileChildren(
  AuthedClientsRouteChildren,
)

interface AuthedRouteChildren {
  AuthedAuditRoute: typeof AuthedAuditRoute
  AuthedClientsRoute: typeof AuthedClientsRouteWithChildren
  AuthedInstancesRoute: typeof AuthedInstancesRoute
  AuthedQueueRoute: typeof AuthedQueueRoute
  AuthedTopupsRoute: typeof AuthedTopupsRoute
  AuthedIndexRoute: typeof AuthedIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedAuditRoute: AuthedAuditRoute,
  AuthedClientsRoute: AuthedClientsRouteWithChildren,
  AuthedInstancesRoute: AuthedInstancesRoute,
  AuthedQueueRoute: AuthedQueueRoute,
  AuthedTopupsRoute: AuthedTopupsRoute,
  AuthedIndexRoute: AuthedIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
